apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubooquity-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/neravy-books/ubooquity/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubooquity-config-pvc
  namespace: biblioteca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubooquity-books-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/neravy-books/ubooquity/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubooquity-books-pvc
  namespace: biblioteca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
