apiVersion: v1
kind: PersistentVolume
metadata:
  name: libros-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/neravy-books/ubooquity/books # Mantenemos tu ruta actual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libros-pvc
  namespace: biblioteca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
