apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config-pvc
  namespace: biblioteca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-libros-pvc
  namespace: biblioteca
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
