apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: biblioteca
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            autoindex on;        # Activa el listado de archivos
            autoindex_exact_size off;
            autoindex_localtime on;
            charset utf-8;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexador-libros
  namespace: biblioteca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexador
  template:
    metadata:
      labels:
        app: indexador
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: libros-storage
          mountPath: /usr/share/nginx/html
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          limits:
            memory: "64Mi" # Sobra RAM por todos lados
            cpu: "50m"
      volumes:
      - name: libros-storage
        persistentVolumeClaim:
          claimName: libros-pvc
      - name: config-volume
        configMap:
          name: nginx-config
