apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubooquity
  namespace: biblioteca
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ubooquity
  template:
    metadata:
      labels:
        app: ubooquity
    spec:
      containers:
      - name: ubooquity
        image: linuxserver/ubooquity:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Lima"
        - name: MAX_MEM
          value: "512"
        ports:
        - containerPort: 2202
          name: library
        - containerPort: 2203
          name: admin
        volumeMounts:
        - name: config
          mountPath: /config
        - name: books
          mountPath: /books
      volumes:
      - name: config
        hostPath:
          path: /opt/neravy-books/ubooquity/config
          type: DirectoryOrCreate
      - name: books
        hostPath:
          path: /opt/neravy-books/ubooquity/books
          type: DirectoryOrCreate
