apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubooquity
  namespace: biblioteca
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ubooquity
  template:
    metadata:
      labels:
        app: ubooquity
    spec:
      # ELIMINAMOS el securityContext de aquí porque rompe el inicio de LinuxServer
      containers:
      - name: ubooquity
        image: linuxserver/ubooquity:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Lima"
        - name: MAX_MEM
          value: "256"
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -XX:+UseSerialGC"
        ports:
        - containerPort: 2202
          name: library
        - containerPort: 2203
          name: admin
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: config-vol
          mountPath: /config
        - name: books-vol
          mountPath: /books
      volumes:
      - name: config-vol
        persistentVolumeClaim:
          claimName: ubooquity-config-pvc
      - name: books-vol
        persistentVolumeClaim:
          claimName: ubooquity-books-pvc
