apiVersion: v1
kind: Service
metadata:
  name: ubooquity-service
  namespace: biblioteca
spec:
  type: NodePort
  selector:
    app: ubooquity
  ports:
    - name: library-port
      protocol: TCP
      port: 8443        # Puerto para el iPhone/Cloudflare
      targetPort: 2202  # Puerto interno real
      nodePort: 30443   # Puerto físico en Ubuntu
    - name: admin-port
      protocol: TCP
      port: 2203
      targetPort: 2203
      nodePort: 32203   # Puerto para la configuración inicial
