apiVersion: v1
kind: Service
metadata:
  name: indexador-service
  namespace: biblioteca
spec:
  type: NodePort
  selector:
    app: indexador
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30443 # Tu puerta de entrada desde Cloudflare
